### ISSUE TITLE
flexisip-error-FirebaseV1AccessTokenProvider

### ISSUE THREAD

**Issue by nikoclk23** [BelledonneCommunications/flexisip#200]
I install flexisip server bc-flexisip.x86_64   2.3.5-0.pre.7+b136ab6e.el8
When i try to test push notification i have this error

` [root@flex-02-usc1-rockylinux-8 bin]# ./flexisip_pusher --pn-provider fcm --pn-param 434972726999 --pn-prid cZ3tNtusShCLike2NxrJHx:APA91bFIRshYXvSpKs1Cn65k04NXXANZzaWsuNf2ohsqSHhPb-0_HlJqiPJskbTLPKcUyopNtMuAWRzmG_gYhIArMy1GCP1mRDOGrq9RDVysqC3KNvc4LoZY9nUFZ5-inFq2fs2GHT6D --key /etc/flexisip/service-account-4bee9062b33f.json --debug
Writing logs in : /var/opt/belledonne-communications/log/flexisip/flexisip-pusher.log
2024-11-04 19:27:17:785 flexisip-error-FirebaseV1AccessTokenProvider: an error has occurred during script execution, error = "failed to parse script output [exit_code = 0]"
2024-11-04 19:27:17:785 flexisip-warning-FirebaseV1AuthenticationManager[intercom]: failed to get access token, automatic retry in 60000ms
2024-11-04 19:27:17:785 flexisip-debug-FirebaseV1Client[0x1a8cf40]: constructing FirebaseV1Client
2024-11-04 19:27:17:785 flexisip-debug-Http2Client[0x1a95100]: constructing Http2Client with TlsConnection[0x1a74850]
2024-11-04 19:27:17:785 flexisip-debug-Adding firebase push notification client [434972726999]
2024-11-04 19:27:17:785 flexisip-debug-FirebaseV1 request[0x1a93e30] creation, payload:
{
        "message":{
                "token": "cZ3tNtusShCLike2NxrJHx:APA91bFIRshYXvSpKs1Cn65k04NXXANZzaWsuNf2ohsqSHhPb-0_HlJqiPJskbTLPKcUyopNtMuAWRzmG_gYhIArMy1GCP1mRDOGrq9RDVysqC3KNvc4LoZY9nUFZ5-inFq2fs2GHT6D",
                "android":{
                        "priority": "high",
                        "ttl": "2419200s",
                        "data":{
                                "uuid":"",
                                "from-uri":"sip:pusher@sip.example.org",
                                "display-name":"Pusher",
                                "call-id":"fb14b5fe-a9ab-1231-9485-7d582244ba3d",
                                "sip-from":"Pusher",
                                "loc-key":"Push test message.",
                                "loc-args":"Pusher",
                                "send-time":"2024-11-04 19:27:17",
                                "custom-payload":"{}"
                        }
                }
        }
}
2024-11-04 19:27:17:785 flexisip-debug-FirebaseV1 request[0x1a93e30] creation, headers:
:method = POST
:scheme = https
:path = /v1/projects/intercom/messages:send
:authority = fcm.googleapis.com:443
content-type = application/json

2024-11-04 19:27:17:785 flexisip-debug-Request[0x1a93e30]: switching state from NotSubmitted -> InProgress
2024-11-04 19:27:17:785 flexisip-error-Http2Client[0x1a95100]: failed to add authentication in request header
2024-11-04 19:27:17:785 flexisip-debug-Request[0x1a93e30]: switching state from InProgress -> Failed
2024-11-04 19:27:17:785 flexisip-message-1 push notification(s) sent, 0 successfully and 1 failed.
2024-11-04 19:27:17:785 flexisip-message-There are failed requests, relaunch with --debug to consult exact error cause.
2024-11-04 19:27:17:785 flexisip-message-job is done, thanks for using ./flexisip_pusher. Bye!
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [B2bua]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [Transcoder]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [StatisticsCollector]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [SanityChecker]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [Router]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [Registrar]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [RegEvent]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [PushNotification]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [Presence]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [Redirect]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [NatHelper]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [MediaRelay]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [LoadBalancer]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [GatewayAdapter]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [GarbageIn]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [Forward]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [ContactRouteInserter]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [Capabilities]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [Authentication]...
2024-11-04 19:27:17:786 flexisip-message-Unregistering module info [DoSProtection]..  `

`.`

**Comment by Failxxx** [comment]
Hello @nikoclk23,
Thank you for taking time to report a problem with Flexisip.

Can you please execute the following command ?
`/opt/belledonne-communications/share/flexisip/firebase_v1_get_access_token.py -f /etc/flexisip/service-account-4bee9062b33f.json`
I guess something went wrong happened while Flexisip was trying to get the access token. Running this command should give us more information. The explanatory string is not very helpful here.

Sincerely,
Félix.

**Comment by nikoclk23** [comment]
Hi @Failxxx ,

when executing the command I get this response:

`[root@flex-02-usc1-rockylinux-8 bin]# /opt/belledonne-communications/share/flexisip/firebase_v1_get_access_token.py -f /etc/flexisip/service-account-4bee9062b33f.json`

```
/usr/local/lib/python3.6/site-packages/google/auth/crypt/_cryptography_rsa.py:22: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  import cryptography.exceptions
{"state": "SUCCESS", "data": {"token": "ya29.c.c0ASRK0GY3qaP5pXFy92P-TwKics5ifFIwB8XpMDcHuH8c7-euY6_X7ZBuLZhKWEYT5erItRW14idU-WSuCAhrNzwHmY6x603tU-VHdIPVEDmHg-GmWg9ZjdG8iB0CJ8PD0_LrPTfMZaHnK1U50O5h5Av9ApXeatWQQJiLCG0_8zwsofIDnPXiuovQlK2TwaWvqBNs-B7QLx1RjL_h0CXhNuHi8lZ1CSN3obPrdCDFOOb19HqJ9UTc_Ne4hP67O7PPl3EvsmWKyAqApAHVsHJ2pMvmzPYTA1a77ZuOrJM9C1qgVzbr8qigMUhCXjHO8vkm-IesWtkihYVBs_rSlyx3W7UkvYenhzTYsA-VZedSrm6B2hjeLG5OsODyE385A6cQr1WV_UR_XnW66sXeWQnijxV6gsJBXsg0QYqR3M8MXS6YQ_7y922Vpz-4qhue0Uigg38rB7Vp3WJlfF3Ztorb5OWYymsBtJwxXltkpa7-cIJMr39X2zXQqYywXg0_ucjkYXVz69o8ol7cuWYF7F2MpxwmjJRaJuUBbmpkSr4n7uldW9cZ4kYomJSpjFhkJsRMYzk1lZWyu-btQeUFi3J24MStVpw5nlUo-z8W-mXrpmb8Mgj4pjtrRpwliS2Otbon5Qd-y1VgVbg716nZJIuycZjBUvBugkQ_xmeocjgbSMSnq_SgcOkWhVblvu9cI99edzIQxmj8OozuMlz-t7MWw0QswYYh4RS224l3hJOJ4njw47hwIx9W5u1OvXZ-I2YeIw4SojByd1YRwIUq3QRaXbuSF7rfS78z2i27uwXW50i5Ykk0J_g3teQbrkbcSRhjdumZ3v_zXu3JOchUjig3S-u1JtZ7Ihqu-5m_0rJZ19Rv2BiIs_8mBJhdle7t97wuSohM19f6BXqe8OnpVdw-gFM_3-zlSkeZ1t4-_ZBniRJjUgduVMpe75yv-JZwYYino9_f7vYSZujSVk43-nOQymmrQmdjFqJ6Bm6WfYZaRXqZalO0Vj7y2Qh", "lifetime": 3598}, "warnings": []}
```

**Comment by Failxxx** [comment]
Perfect, thank you very much.
The output is indeed ill-formed (warning message breaks the output parsing operation).
I will push a fix as soon as possible.

Félix.

**Comment by nikoclk23** [comment]
thanks for the prompt reply, I will be waiting for the fix.

Best

**Comment by Failxxx** [comment]
Fixed in ccf3b2138a1aea1964a5331eed6f86b1a1d58b6b
Can you test again please ?

Félix.

**Comment by nikoclk23** [comment]
Hi Felix, sorry for the delay in my response.
I upgraded to version bc-flexisip-2.3.5-0.pre.8+ccf3b213, but the error is still present.

```
[root@flex-02-usc1-rockylinux-8 ]# yum list bc-flexisip
Last metadata expiration check: 1:47:35 ago on Fri 15 Nov 2024 12:48:26 PM UTC.
Installed Packages
bc-flexisip.x86_64                                                                     1:2.3.5-0.pre.7+b136ab6e.el8                                                                     @BC_hotfix
Available Packages
bc-flexisip.x86_64                                                                     1:2.3.5-0.pre.8+ccf3b213.el8                                                                     BC_hotfix 
[root@flex-02-usc1-rockylinux-8 ]# yum install bc-flexisip-2.3.4
Last metadata expiration check: 1:47:51 ago on Fri 15 Nov 2024 12:48:26 PM UTC.
Dependencies resolved.
==================================================================================================================================================================================================
 Package                                         Architecture                               Version                                           Repository                                     Size
==================================================================================================================================================================================================
Downgrading:
 bc-flexisip                                     x86_64                                     1:2.3.4-1.el8                                     BC_stable                                     8.1 M

Transaction Summary
==================================================================================================================================================================================================
Downgrade  1 Package

Total download size: 8.1 M
Is this ok [y/N]: y
Downloading Packages:
bc-flexisip-2.3.4-1.el8.x86_64.rpm                                                                                                                                3.5 MB/s | 8.1 MB     00:02    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                             3.5 MB/s | 8.1 MB     00:02     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                          1/1 
  Running scriptlet: bc-flexisip-1:2.3.4-1.el8.x86_64                                                                                                                                         1/1 
  Downgrading      : bc-flexisip-1:2.3.4-1.el8.x86_64                                                                                                                                         1/2 
warning: /etc/flexisip/flexisip.conf created as /etc/flexisip/flexisip.conf.rpmnew

  Running scriptlet: bc-flexisip-1:2.3.4-1.el8.x86_64                                                                                                                                         1/2 
File context for /var/opt/belledonne-communications/log(/.*)? already defined, modifying instead
File context for /var/opt/belledonne-communications/flexisip/b2b(/.*)? already defined, modifying instead

  Running scriptlet: bc-flexisip-1:2.3.5-0.pre.7+b136ab6e.el8.x86_64                                                                                                                          2/2 
  Cleanup          : bc-flexisip-1:2.3.5-0.pre.7+b136ab6e.el8.x86_64                                                                                                                          2/2 
  Running scriptlet: bc-flexisip-1:2.3.5-0.pre.7+b136ab6e.el8.x86_64                                                                                                                          2/2 
  Verifying        : bc-flexisip-1:2.3.4-1.el8.x86_64                                                                                                                                         1/2 
  Verifying        : bc-flexisip-1:2.3.5-0.pre.7+b136ab6e.el8.x86_64                                                                                                                          2/2 

Downgraded:
  bc-flexisip-1:2.3.4-1.el8.x86_64                                                                                                                                                                

Complete!
[root@flex-02-usc1-rockylinux-8 ]# 
[root@flex-02-usc1-rockylinux-8 ]# 
[root@flex-02-usc1-rockylinux-8 ]# 
[root@flex-02-usc1-rockylinux-8 ]# 
[root@flex-02-usc1-rockylinux-8 ]# 
[root@flex-02-usc1-rockylinux-8 ]# cd /opt/belledonne-communications/bin/
[root@flex-02-usc1-rockylinux-8 bin]# ./flexisip_pusher --pn-provider fcm --pn-param 434972726999 --pn-prid cZ3tNtusShCLike2NxrJHx:APA91bFIRshYXvSpKs1Cn65k04NXXANZzaWsuNf2ohsqSHhPb-0_HlJqiPJskbTLPKcUyopNtMuAWRzmG_gYhIArMy1GCP1mRDOGrq9RDVysqC3KNvc4LoZY9nUFZ5-inFq2fs2GHT6D --key /etc/flexisip/intercom.json --debug
Writing logs in : /var/opt/belledonne-communications/log/flexisip/flexisip-pusher.log
2024-11-15 14:38:56:648 flexisip-error-FirebaseV1AccessTokenProvider: an error has occurred during script execution, error = "failed to parse script output [exit_code = 0]"
2024-11-15 14:38:56:648 flexisip-warning-FirebaseV1AuthenticationManager[intercom]: failed to get access token, automatic retry in 60000ms
2024-11-15 14:38:56:648 flexisip-debug-FirebaseV1Client[0x11cdef0]: constructing FirebaseV1Client
2024-11-15 14:38:56:649 flexisip-debug-Http2Client[0x11d6090]: constructing Http2Client with TlsConnection[0x1184630]
2024-11-15 14:38:56:649 flexisip-debug-Adding firebase push notification client [434972726999]
2024-11-15 14:38:56:649 flexisip-debug-FirebaseV1 request[0x11d4dd0] creation, payload:
{
        "message":{
                "token": "cZ3tNtusShCLike2NxrJHx:APA91bFIRshYXvSpKs1Cn65k04NXXANZzaWsuNf2ohsqSHhPb-0_HlJqiPJskbTLPKcUyopNtMuAWRzmG_gYhIArMy1GCP1mRDOGrq9RDVysqC3KNvc4LoZY9nUFZ5-inFq2fs2GHT6D",
                "android":{
                        "priority": "high",
                        "ttl": "2419200s",
                        "data":{
                                "uuid":"",
                                "from-uri":"sip:pusher@sip.example.org",
                                "display-name":"Pusher",
                                "call-id":"fb14b5fe-a9ab-1231-9485-7d582244ba3d",
                                "sip-from":"Pusher",
                                "loc-key":"Push test message.",
                                "loc-args":"Pusher",
                                "send-time":"2024-11-15 14:38:56",
                                "custom-payload":"{}"
                        }
                }
        }
}
2024-11-15 14:38:56:649 flexisip-debug-FirebaseV1 request[0x11d4dd0] creation, headers:
:method = POST
:scheme = https
:path = /v1/projects/intercom/messages:send
:authority = fcm.googleapis.com:443
content-type = application/json

2024-11-15 14:38:56:649 flexisip-debug-Request[0x11d4dd0]: switching state from NotSubmitted -> InProgress
2024-11-15 14:38:56:649 flexisip-error-Http2Client[0x11d6090]: failed to add authentication in request header
2024-11-15 14:38:56:649 flexisip-debug-Request[0x11d4dd0]: switching state from InProgress -> Failed
2024-11-15 14:38:56:649 flexisip-message-1 push notification(s) sent, 0 successfully and 1 failed.
2024-11-15 14:38:56:649 flexisip-message-There are failed requests, relaunch with --debug to consult exact error cause.
2024-11-15 14:38:56:649 flexisip-message-job is done, thanks for using ./flexisip_pusher. Bye!
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [B2bua]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [Transcoder]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [StatisticsCollector]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [SanityChecker]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [Router]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [Registrar]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [RegEvent]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [PushNotification]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [Presence]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [Redirect]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [NatHelper]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [MediaRelay]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [LoadBalancer]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [GatewayAdapter]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [GarbageIn]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [Forward]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [ContactRouteInserter]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [Capabilities]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [Authentication]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [DoSProtection]...
[root@flex-02-usc1-rockylinux-8 bin]# [root@flex-02-usc1-rockylinux-8 ]# yum list bc-flexisip
Last metadata expiration check: 1:47:35 ago on Fri 15 Nov 2024 12:48:26 PM UTC.
Installed Packages
bc-flexisip.x86_64                                                                     1:2.3.5-0.pre.7+b136ab6e.el8                                                                     @BC_hotfix
Available Packages
bc-flexisip.x86_64                                                                     1:2.3.5-0.pre.8+ccf3b213.el8                                                                     BC_hotfix 
[root@flex-02-usc1-rockylinux-8 ]# yum install bc-flexisip-2.3.4
Last metadata expiration check: 1:47:51 ago on Fri 15 Nov 2024 12:48:26 PM UTC.
Dependencies resolved.
==================================================================================================================================================================================================
 Package                                         Architecture                               Version                                           Repository                                     Size
==================================================================================================================================================================================================
Downgrading:
 bc-flexisip                                     x86_64                                     1:2.3.4-1.el8                                     BC_stable                                     8.1 M

Transaction Summary
==================================================================================================================================================================================================
Downgrade  1 Package

Total download size: 8.1 M
Is this ok [y/N]: y
Downloading Packages:
bc-flexisip-2.3.4-1.el8.x86_64.rpm                                                                                                                                3.5 MB/s | 8.1 MB     00:02    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                             3.5 MB/s | 8.1 MB     00:02     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                          1/1 
  Running scriptlet: bc-flexisip-1:2.3.4-1.el8.x86_64                                                                                                                                         1/1 
  Downgrading      : bc-flexisip-1:2.3.4-1.el8.x86_64                                                                                                                                         1/2 
warning: /etc/flexisip/flexisip.conf created as /etc/flexisip/flexisip.conf.rpmnew

  Running scriptlet: bc-flexisip-1:2.3.4-1.el8.x86_64                                                                                                                                         1/2 
File context for /var/opt/belledonne-communications/log(/.*)? already defined, modifying instead
File context for /var/opt/belledonne-communications/flexisip/b2b(/.*)? already defined, modifying instead

  Running scriptlet: bc-flexisip-1:2.3.5-0.pre.7+b136ab6e.el8.x86_64                                                                                                                          2/2 
  Cleanup          : bc-flexisip-1:2.3.5-0.pre.7+b136ab6e.el8.x86_64                                                                                                                          2/2 
  Running scriptlet: bc-flexisip-1:2.3.5-0.pre.7+b136ab6e.el8.x86_64                                                                                                                          2/2 
  Verifying        : bc-flexisip-1:2.3.4-1.el8.x86_64                                                                                                                                         1/2 
  Verifying        : bc-flexisip-1:2.3.5-0.pre.7+b136ab6e.el8.x86_64                                                                                                                          2/2 

Downgraded:
  bc-flexisip-1:2.3.4-1.el8.x86_64                                                                                                                                                                

Complete!
[root@flex-02-usc1-rockylinux-8 ]# 
[root@flex-02-usc1-rockylinux-8 ]# 
[root@flex-02-usc1-rockylinux-8 ]# 
[root@flex-02-usc1-rockylinux-8 ]# 
[root@flex-02-usc1-rockylinux-8 ]# 
[root@flex-02-usc1-rockylinux-8 ]# cd /opt/belledonne-communications/bin/
[root@flex-02-usc1-rockylinux-8 bin]# ./flexisip_pusher --pn-provider fcm --pn-param 434972726999 --pn-prid cZ3tNtusShCLike2NxrJHx:APA91bFIRshYXvSpKs1Cn65k04NXXANZzaWsuNf2ohsqSHhPb-0_HlJqiPJskbTLPKcUyopNtMuAWRzmG_gYhIArMy1GCP1mRDOGrq9RDVysqC3KNvc4LoZY9nUFZ5-inFq2fs2GHT6D --key /etc/flexisip/intercom.json --debug
Writing logs in : /var/opt/belledonne-communications/log/flexisip/flexisip-pusher.log
2024-11-15 14:38:56:648 flexisip-error-FirebaseV1AccessTokenProvider: an error has occurred during script execution, error = "failed to parse script output [exit_code = 0]"
2024-11-15 14:38:56:648 flexisip-warning-FirebaseV1AuthenticationManager[intercom]: failed to get access token, automatic retry in 60000ms
2024-11-15 14:38:56:648 flexisip-debug-FirebaseV1Client[0x11cdef0]: constructing FirebaseV1Client
2024-11-15 14:38:56:649 flexisip-debug-Http2Client[0x11d6090]: constructing Http2Client with TlsConnection[0x1184630]
2024-11-15 14:38:56:649 flexisip-debug-Adding firebase push notification client [434972726999]
2024-11-15 14:38:56:649 flexisip-debug-FirebaseV1 request[0x11d4dd0] creation, payload:
{
        "message":{
                "token": "cZ3tNtusShCLike2NxrJHx:APA91bFIRshYXvSpKs1Cn65k04NXXANZzaWsuNf2ohsqSHhPb-0_HlJqiPJskbTLPKcUyopNtMuAWRzmG_gYhIArMy1GCP1mRDOGrq9RDVysqC3KNvc4LoZY9nUFZ5-inFq2fs2GHT6D",
                "android":{
                        "priority": "high",
                        "ttl": "2419200s",
                        "data":{
                                "uuid":"",
                                "from-uri":"sip:pusher@sip.example.org",
                                "display-name":"Pusher",
                                "call-id":"fb14b5fe-a9ab-1231-9485-7d582244ba3d",
                                "sip-from":"Pusher",
                                "loc-key":"Push test message.",
                                "loc-args":"Pusher",
                                "send-time":"2024-11-15 14:38:56",
                                "custom-payload":"{}"
                        }
                }
        }
}
2024-11-15 14:38:56:649 flexisip-debug-FirebaseV1 request[0x11d4dd0] creation, headers:
:method = POST
:scheme = https
:path = /v1/projects/intercom/messages:send
:authority = fcm.googleapis.com:443
content-type = application/json

2024-11-15 14:38:56:649 flexisip-debug-Request[0x11d4dd0]: switching state from NotSubmitted -> InProgress
2024-11-15 14:38:56:649 flexisip-error-Http2Client[0x11d6090]: failed to add authentication in request header
2024-11-15 14:38:56:649 flexisip-debug-Request[0x11d4dd0]: switching state from InProgress -> Failed
2024-11-15 14:38:56:649 flexisip-message-1 push notification(s) sent, 0 successfully and 1 failed.
2024-11-15 14:38:56:649 flexisip-message-There are failed requests, relaunch with --debug to consult exact error cause.
2024-11-15 14:38:56:649 flexisip-message-job is done, thanks for using ./flexisip_pusher. Bye!
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [B2bua]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [Transcoder]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [StatisticsCollector]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [SanityChecker]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [Router]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [Registrar]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [RegEvent]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [PushNotification]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [Presence]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [Redirect]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [NatHelper]...
2024-11-15 14:38:56:649 flexisip-message-Unregistering module info [MediaRelay]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [LoadBalancer]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [GatewayAdapter]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [GarbageIn]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [Forward]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [ContactRouteInserter]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [Capabilities]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [Authentication]...
2024-11-15 14:38:56:650 flexisip-message-Unregistering module info [DoSProtection]...
[root@flex-02-usc1-rockylinux-8 bin]# 
```

**Comment by Failxxx** [comment]
Hello @nikoclk23,
Thank you a lot for your reply,

Can you please re-execute the following command and paste the output here ?
/opt/belledonne-communications/share/flexisip/firebase_v1_get_access_token.py -f /etc/flexisip/service-account-4bee9062b33f.json
I do not understand why my fix does not do the job. I tested it manually and I thought it worked.

Sincerely,
Félix.

**Comment by Failxxx** [comment]
Alright, I get it. My bad. I will push a new fix.

**Comment by Failxxx** [comment]
It should now be fixed. I pushed a new commit (4eef5ee0f2af1e7dee35e54a1f99e3d915e7f885).
Can you please test again with `bc-flexisip-2.3.5-0.pre.9+d16e251c`?

**Comment by nikoclk23** [comment]
Hi Felix, fix is work fine now
